import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

async function HealthBadgeServer() {
    try {
        const base = process.env.NEXT_PUBLIC_API_BASE ?? "http://localhost:3001";
        const res = await fetch(`${base}/platform/health`, { cache: "no-store" });
        const data = (await res.json()) as { db: boolean; docker: boolean };
        return (
            <div style={{ display: "flex", gap: 8 }}>
                <span>DB {data.db ? "✅" : "❌"}</span>
                <span>Docker {data.docker ? "✅" : "❌"}</span>
            </div>
        );
    } catch {
        return (
            <div style={{ display: "flex", gap: 8 }}>
                <span>DB ❌</span>
                <span>Docker ❌</span>
            </div>
        );
    }
}

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: 12, borderBottom: "1px solid #eee" }}>
					<strong>Deeployable</strong>
                    {/* Indicadores de salud (Server Component) */}
                    <HealthBadgeServer />
				</header>
				{children}
			</body>
		</html>
	);
}
